hospital/home/urls.py
from django.conf.urls import patterns, url
from .views import login, logout


urlpatterns = patterns(
    '',
    url(r'^$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
)

hospital/hospital/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from rest_framework import routers
from patient.views import PatientViewSet
from expose_the_user.views import UserViewSet
from medicine.views import MedicineViewSet, MedicinePerConsultationViewSet
from consultation.views import MedicalConsultationViewSet


router = routers.DefaultRouter()
router.register(r'patients', PatientViewSet)
router.register(r'users', UserViewSet)
router.register(r'medicines', MedicineViewSet)
router.register(r'medicines-per-consultation', MedicinePerConsultationViewSet)
router.register(r'consultations', MedicalConsultationViewSet)


urlpatterns = patterns(
    '',
    # Grappelli urls.
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Browsable API.
    url(r'^api/', include(router.urls)),
    url(
        r'^api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework'
        )
    ),
    # Home app.
    url(r'^', include('home.urls', namespace='home_app')),
    # Patient app.
    url(r'^patients/', include('patient.urls', namespace='patient_app')),
    # User app.
    url(r'^users/', include('expose_the_user.urls', namespace='user_app')),
    # Medicine app.
    url(r'^medicines/', include('medicine.urls', namespace='medicine_app')),
    # Medicine app.
    url(
        r'^consultation/',
        include('consultation.urls', namespace='consultation_app')
    ),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        url(r'^rosetta/', include('rosetta.urls')),
    )

hospital/medicine/urls.py
from django.conf.urls import patterns, url
from .views import medicine_list_view, MedicineDetailView, MedicineDeleteView
from .views import medicine_create_view, medicine_update_view


urlpatterns = patterns(
    '',
    url(r'^$', medicine_list_view, name='medicines-list'),
    url(
        r'^create/$',
        medicine_create_view,
        name='medicines-create',
    ),
    url(
        r'^delete/(?P<code>[\w]+)/$',
        MedicineDeleteView.as_view(),
        name='medicines-delete',
    ),
    url(
        r'^update/(?P<code>[\w]+)/$',
        medicine_update_view,
        name='medicines-update',
    ),
    url(
        r'^(?P<code>[\w]+)/$',
        MedicineDetailView.as_view(),
        name='medicines-detail',
    ),
)

hospital/patient/urls.py
from django.conf.urls import patterns, url
from .views import patient_list_view, PatientDetailView, PatientDeleteView
from .views import patient_create_view, patient_update_view


urlpatterns = patterns(
    '',
    url(r'^$', patient_list_view, name='patients-list'),
    url(
        r'^create/$',
        patient_create_view,
        name='patients-create',
    ),
    url(
        r'^delete/(?P<pk>[\w]+)/$',
        PatientDeleteView.as_view(),
        name='patients-delete',
    ),
    url(
        r'^update/(?P<dni>[\w]+)/$',
        patient_update_view,
        name='patients-update',
    ),
    url(
        r'^(?P<pk>[\w]+)/$',
        PatientDetailView.as_view(),
        name='patients-detail',
    ),
)

hospital/medicine/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Medicine(models.Model):
    code = models.CharField(
        max_length=50,
        primary_key=True,
        verbose_name=_('codigo'),
    )
    name = models.CharField(
        max_length=250,
        verbose_name=_('name'),
    )
    description = models.CharField(
        max_length=350,
        blank=True,
        verbose_name=_('description'),
    )
    medicine_type = models.CharField(
        max_length=350,
        blank=True,
        verbose_name=_('medicine type'),
    )
    amount = models.PositiveIntegerField(
        verbose_name=_('amount'),
    )

    def __unicode__(self):
        return unicode(self.code)

    class Meta:
        db_table = 'medicine'
        verbose_name = _('medicine')


class MedicinePerConsultation(models.Model):
    medical_consultation = models.ForeignKey(
        'consultation.MedicalConsultation',
        verbose_name=_('medical consultation'),
    )
    medicine = models.ForeignKey(
        'medicine.Medicine',
        verbose_name=_('medicine'),
    )
    amount = models.PositiveIntegerField(
        verbose_name=_('amount'),
    )

    def __unicode__(self):
        return unicode(self.id)

    class Meta:
        db_table = 'medicine_per_consultation'
        verbose_name = _('medicine per consultation')

hospital/medicine/views.py
from django.shortcuts import render_to_response
from rest_framework import viewsets
from rest_framework import permissions
from hospital.permissions import IsSuperuserOrReadOnly
from hospital.mixins import LoginRequiredMixin
from .serializers import MedicineSerializer, MedicinePerConsultationSerializer
from .models import Medicine, MedicinePerConsultation
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _


class MedicinePerConsultationViewSet(viewsets.ModelViewSet):

    queryset = MedicinePerConsultation.objects.all()
    serializer_class = MedicinePerConsultationSerializer
    permission_classes = (
        permissions.IsAuthenticatedOrReadOnly,
    )
    filter_fields = (
        'medical_consultation',
        'medicine',
    )


class MedicineViewSet(viewsets.ModelViewSet):

    queryset = Medicine.objects.all()
    serializer_class = MedicineSerializer
    permission_classes = (
        permissions.IsAuthenticatedOrReadOnly,
        IsSuperuserOrReadOnly,
    )
    filter_fields = (
        'name',
        'medicine_type',
    )


def medicine_list_view(request):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    medicines = None
    search = request.GET.get("search", False)
    if search:
        try:
            medicines = Medicine.objects.filter(code__icontains=search) | \
                Medicine.objects.filter(name__icontains=search) | \
                Medicine.objects.filter(medicine_type__icontains=search)
        except Exception, e:
            medicines = None
    else:
        medicines = Medicine.objects.all()

    ctx = {'medicines': medicines}

    return render_to_response(
        'medicine/list.html',
        ctx,
        context_instance=RequestContext(request),
    )


class MedicineDetailView(LoginRequiredMixin, DetailView):
    model = Medicine
    pk_url_kwarg = 'code'
    template_name = 'medicine/detail.html'


# solo como superuser
class MedicineDeleteView(LoginRequiredMixin, DeleteView):
    model = Medicine
    success_url = reverse_lazy('medicine_app:medicines-list')
    pk_url_kwarg = 'code'
    template_name = 'medicine/delete.html'


def record_medicine(request):
    code = request.POST['code']
    name = request.POST['name']
    description = request.POST['description']
    medicine_type = request.POST['medicine_type']
    amount = request.POST['amount']

    medicine = Medicine.objects.create(
        code=code,
        name=name,
        description=description,
        medicine_type=medicine_type,
        amount=amount,
    )

    return medicine


def medicine_create_view(request):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            medicine = record_medicine(request)
            if medicine:
                return HttpResponseRedirect(
                    reverse('medicine_app:medicines-list')
                )

        return render_to_response(
            'medicine/create.html',
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])


def update_medicine(request, code):
    name = request.POST['name']
    description = request.POST['description']
    medicine_type = request.POST['medicine_type']
    amount = request.POST['amount']

    medicine = get_object_or_404(Medicine, pk=code)
    medicine.name = name
    medicine.description = description
    medicine.medicine_type = medicine_type
    medicine.amount = amount
    medicine.save()

    return medicine


def medicine_update_view(request, code):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            medicine = update_medicine(request, code)
            if medicine:
                return HttpResponseRedirect(
                    reverse('medicine_app:medicines-list')
                )

        medicine = get_object_or_404(Medicine, pk=code)

        ctx = {'medicine': medicine}

        return render_to_response(
            'medicine/update.html',
            ctx,
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])

hospital/templates/medicine/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Agregar Medicamento <i class="fa fa-medkit"></i></h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}

      <div class="form-group">
        <label for="code">Código</label>
        <input name="code" id="code" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="name">Nombre</label>
        <input name="name" id="name" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="description">Descripción</label>
        <input name="description" id="description" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="medicine_type">Tipo</label>
        <input name="medicine_type" id="medicine_type" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="amount">Cantidad</label>
        <input name="amount" id="amount" type="number" class="form-control" required>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/> Crear</button>
      </p>
    </form>

    <p>
      <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
  </article>

{% endblock content %}

hospital/templates/medicine/delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-danger">

  <div class="panel-heading">
    <h1 class="panel-title">
      Eliminación del Medicamento <strong>{{ object.code }} - {{ object.name|title }}</strong> <i class="fa fa-trash"></i>
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post">
      {% csrf_token %}
      <h2>¿Está seguro que desea eliminar al medicamento <strong>{{ object.code }} - {{ object.name|title }}</strong>?</h2>
      <p>
        <button type="submit" class="btn btn-danger btn-block"/>Confirmar</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-success btn-block"> Volver a la Lista </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-update' object.code %}" class="btn btn-primary btn-block"> Modificar Medicamento </a>
      </p>
    </section>

  </article>

</div>

{% endblock content %}

hospital/templates/medicine/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Detalle del Medicamento <i class="fa fa-medkit"></i>
    </h1>
  </div>

  <article class="panel-body">
    {% if object.code %}
      <p>Código: <strong>{{ object.code }}</strong></p>
    {% endif %}
    
    {% if object.name %}
      <p>Nombre: <strong>{{ object.name|title }}</strong></p>
    {% endif %}
    
    {% if object.description %}
      <p>Descripción: <strong>{{ object.description }}</strong></p>
    {% endif %}
    
    {% if object.medicine_type %}
      <p>Tipo: <strong>{{ object.medicine_type|title }}</strong></p>
    {% endif %}

    {% if object.amount %}
      <p>Cantidad: <strong>{{ object.amount }}</strong></p>
    {% endif %}
 
    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista de Pacientes </a>
    </p>
    {% if user.is_superuser %}
      <p>
        <a href="{% url 'medicine_app:medicines-update' object.code %}" class="btn btn-primary btn-block"> Modificar Medicamento </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-delete' object.code %}" class="btn btn-primary btn-block"> Eliminar Medicamento </a>
      </p>
    {% endif %}
  </article>

</div>

{% endblock content %}

hospital/templates/medicine/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not medicines %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    Aún no hay medicamentos, <a href="{% url 'medicine_app:medicines-create' %}">por favor ingrese uno</a>.
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Lista de Medicinas <i class="fa fa-medkit"></i></h1>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Código</th>        
        <th>Nombre</th>        
        <th>Tipo</th>        
        <th>Cantidad</th>        
      </tr>
    </thead>
    <tbody>
      {% for medicine in medicines %}
        <tr>
          <td><a href="{% url 'medicine_app:medicines-detail' medicine.code %}">{{ medicine.code }}</a></td>
          <td>{{ medicine.name }}</td>
          <td>{{ medicine.medicine_type }}</td>
          <td>{{ medicine.amount }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <article class="panel-body">
    <p>
      <a href="{% url 'medicine_app:medicines-create' %}" class="btn btn-success btn-block"> Agregar Medicina </a>
    </p>
  </article>

</div>

{% endblock content %}

hospital/templates/medicine/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Modificar Medicamento <i class="fa fa-medkit"></i></h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}

      <div class="form-group">
        <label for="code">Código</label>
        <input name="code" id="code" type="text" value="{{ medicine.code }}" class="form-control" readonly>
      </div>

      <div class="form-group">
        <label for="name">Nombre</label>
        <input name="name" id="name" type="text" value="{{ medicine.name }}" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="description">Descripción</label>
        <input name="description" id="description" type="text" value="{{ medicine.description }}" class="form-control"name>
      </div>

      <div class="form-group">
        <label for="medicine_type">Tipo</label>
        <input name="medicine_type" id="medicine_type" type="text" value="{{ medicine.medicine_type }}" class="form-control">
      </div>

      <div class="form-group">
        <label for="amount">Cantidad</label>
        <input name="amount" id="amount" type="number" value="{{ medicine.amount }}" class="form-control" required>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/>Modificar</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'medicine_app:medicines-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
      </p>
      <p>
        <a href="{% url 'medicine_app:medicines-delete' medicine.code %}" class="btn btn-primary btn-block"> Eliminar Medicamento </a>
      </p>
    </section>
  </article>
  
</div>

{% endblock content %}