hospital/consultation/urls.py
from django.conf.urls import patterns, url
from .views import medical_consultation, medical_history
from .views import detailed_consultation


urlpatterns = patterns(
    '',
    url(
        r'^(?P<dni>[\w]+)/$',
        medical_consultation,
        name='medical-consultation',
    ),
    url(
        r'^history/(?P<dni>[\w]+)/$',
        medical_history,
        name='medical-history',
    ),
    url(
        r'^detail/(?P<pk>[\w]+)/$',
        detailed_consultation,
        name='detailed-consultation',
    ),
)

hospital/home/urls.py
from django.conf.urls import patterns, url
from .views import login, logout


urlpatterns = patterns(
    '',
    url(r'^$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
)

hospital/hospital/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from rest_framework import routers
from patient.views import PatientViewSet
from expose_the_user.views import UserViewSet
from medicine.views import MedicineViewSet, MedicinePerConsultationViewSet
from consultation.views import MedicalConsultationViewSet


router = routers.DefaultRouter()
router.register(r'patients', PatientViewSet)
router.register(r'users', UserViewSet)
router.register(r'medicines', MedicineViewSet)
router.register(r'medicines-per-consultation', MedicinePerConsultationViewSet)
router.register(r'consultations', MedicalConsultationViewSet)


urlpatterns = patterns(
    '',
    # Grappelli urls.
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Browsable API.
    url(r'^api/', include(router.urls)),
    url(
        r'^api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework'
        )
    ),
    # Home app.
    url(r'^', include('home.urls', namespace='home_app')),
    # Patient app.
    url(r'^patients/', include('patient.urls', namespace='patient_app')),
    # User app.
    url(r'^users/', include('expose_the_user.urls', namespace='user_app')),
    # Medicine app.
    url(r'^medicines/', include('medicine.urls', namespace='medicine_app')),
    # Medicine app.
    url(
        r'^consultation/',
        include('consultation.urls', namespace='consultation_app')
    ),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        url(r'^rosetta/', include('rosetta.urls')),
    )

hospital/medicine/urls.py
from django.conf.urls import patterns, url
from .views import medicine_list_view, MedicineDetailView, MedicineDeleteView
from .views import medicine_create_view, medicine_update_view


urlpatterns = patterns(
    '',
    url(r'^$', medicine_list_view, name='medicines-list'),
    url(
        r'^create/$',
        medicine_create_view,
        name='medicines-create',
    ),
    url(
        r'^delete/(?P<code>[\w]+)/$',
        MedicineDeleteView.as_view(),
        name='medicines-delete',
    ),
    url(
        r'^update/(?P<code>[\w]+)/$',
        medicine_update_view,
        name='medicines-update',
    ),
    url(
        r'^(?P<code>[\w]+)/$',
        MedicineDetailView.as_view(),
        name='medicines-detail',
    ),
)

hospital/patient/urls.py
from django.conf.urls import patterns, url
from .views import patient_list_view, PatientDetailView, PatientDeleteView
from .views import patient_create_view, patient_update_view


urlpatterns = patterns(
    '',
    url(r'^$', patient_list_view, name='patients-list'),
    url(
        r'^create/$',
        patient_create_view,
        name='patients-create',
    ),
    url(
        r'^delete/(?P<pk>[\w]+)/$',
        PatientDeleteView.as_view(),
        name='patients-delete',
    ),
    url(
        r'^update/(?P<dni>[\w]+)/$',
        patient_update_view,
        name='patients-update',
    ),
    url(
        r'^(?P<pk>[\w]+)/$',
        PatientDetailView.as_view(),
        name='patients-detail',
    ),
)

hospital/consultation/models.py
from django.db import models
from django.contrib.auth.models import User
from medicine.models import Medicine
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class MedicalConsultation(models.Model):
    medicines = models.ManyToManyField(
        Medicine,
        through='medicine.MedicinePerConsultation',
        verbose_name=_('medicines'),
    )
    doctor = models.ForeignKey(
        User,
        verbose_name=_('doctor'),
    )
    patient = models.ForeignKey(
        'patient.Patient',
        verbose_name=_('patient'),
    )
    prescription = models.TextField(
        verbose_name=_('prescription'),
    )
    diagnosis = models.TextField(
        verbose_name=_('diagnosis'),
    )
    is_inpatient = models.BooleanField(
        default=True,
        verbose_name=_('is inpatient'),
    )
    date_performed = models.DateTimeField(
        default=timezone.now,
        verbose_name=_('date performed'),
    )

    def __unicode__(self):
        return unicode(self.id)

    class Meta:
        db_table = 'medical_consultation'
        verbose_name = _('medical consultation')

hospital/consultation/views.py
from django.shortcuts import render_to_response
from rest_framework import viewsets
from rest_framework import permissions
from hospital.permissions import IsSuperuserOrReadOnly
from hospital.mixins import LoginRequiredMixin
from .serializers import MedicalConsultationSerializer
from .models import MedicalConsultation
from medicine.models import MedicinePerConsultation
from patient.models import Patient
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _


class MedicalConsultationViewSet(viewsets.ModelViewSet):

    queryset = MedicalConsultation.objects.all()
    serializer_class = MedicalConsultationSerializer
    permission_classes = (
        permissions.IsAuthenticatedOrReadOnly,
    )
    filter_fields = (
        'doctor',
        'patient',
        'is_inpatient',
    )

    def pre_save(self, obj):
        user = self.request.user
        obj.doctor = user
        super(MedicalConsultationViewSet, self).pre_save(obj)


def medical_consultation(request, dni):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    patient = Patient.objects.get(pk=dni)
    ctx = {'patient': patient}

    return render_to_response(
        'consultation/create.html',
        ctx,
        context_instance=RequestContext(request),
    )


def medical_history(request, dni):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    consultations = MedicalConsultation.objects.filter(patient=dni)
    ctx = {
        'consultations': consultations,
        'patient_dni': dni,
    }

    return render_to_response(
        'consultation/list.html',
        ctx,
        context_instance=RequestContext(request),
    )


def detailed_consultation(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    consultation = get_object_or_404(MedicalConsultation, pk=pk)

    medicines_per_consultation = MedicinePerConsultation.objects.filter(
        medical_consultation=pk,
    )
    ctx = {
        'consultation': consultation,
        'medicines_per_consultation': medicines_per_consultation,
    }

    return render_to_response(
        'consultation/detail.html',
        ctx,
        context_instance=RequestContext(request),
    )

hospital/templates/consultation/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Consulta Médica</h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form" id="js-form">
      {% csrf_token %}
      <div class="form-group">
        <label for="patient">Paciente</label>
        <input id="patient" type="text" value="{{ patient.first_name|title }} {{ patient.last_name|title }}" class="form-control" readonly>
      </div>

      <div class="form-group">
        <label for="dni">DNI</label>
        <input id="dni" type="text" value="{{ patient.dni }}" class="form-control js-dni" readonly>
      </div>

      <div class="form-group">
        <label for="diagnosis">Diagnóstico</label>
        <textarea rows="3" name="diagnosis" id="diagnosis" type="text" class="form-control" required></textarea>
      </div>

      <div class="form-group">
        <label for="prescription">Receta médica</label>
        <textarea rows="3" name="prescription" id="prescription" type="text" class="form-control" required></textarea>

        <div class="row row-medicine clone" style="display:none">
          <div class="col-xs-5">
            <span class="col-sm-4 control-label center-label">Medicamento</span>
            <div class="col-sm-8">
              <select class="form-control js-select-medicine">
              </select>
            </div>
          </div>

          <div class="col-xs-4">
            <div class="form-group">
              <span class="col-sm-3 control-label center-label">Cantidad</span>
              <div class="col-sm-9">
                <input class="form-control js-amount-medicine" type="number" name="quantity" min="1" max="50">
              </div>
            </div>
          </div>

          <div class="col-xs-2">
            <i class="fa fa-plus-circle fa-2x fa-add js-add" title="Agregar"></i>
            <i class="fa fa-minus-circle fa-2x fa-delete js-delete" style="display:none" title="Eliminar"></i>
          </div>
        </div>

        <div class="js-container-medicaments"></div>
      </div>

      <div class="checkbox">
        <label>
          <input name="is_inpatient" id="js-isInpatient" type="checkbox"> ¿Será Internado?
        </label>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block js-submit" data-loading-text="Enviando..."/> Crear</button>
      </p>
    </form>

    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
  </article>

{% endblock content %}

{% block js %}
  {{ block.super }}
  <script src="{% static 'js/medicine.js' %}"></script>
{% endblock js %}

hospital/templates/consultation/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not consultations %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    {% if consultation.is_inpatient %}
      El paciente <strong>estuvo internado!</strong>
    {% else %}
      El paciente <strong>recibió atención ambulatoria</strong>
    {% endif %}
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Detalle de la Consulta del <strong>{{ consultation.date_performed|date }}</strong>
    </h1>
  </div>

  <article class="panel-body">

    {% if consultation.patient %}
      <p>Paciente: <strong>{{ consultation.patient.first_name|title }} {{ consultation.patient.last_name|title }}</strong></p>
    {% endif %}

    {% if consultation.diagnosis %}
      <p>Diagnostico: <strong>{{ consultation.diagnosis }}</strong></p>
    {% endif %}

    {% if consultation.prescription %}
      <p>Receta: <strong>{{ consultation.prescription }}</strong></p>
    {% endif %}

    <p>Doctor a Cargo: 
    <strong>
    {% if consultation.doctor.first_name %}
       {{ consultation.doctor.first_name|title }} {{ consultation.doctor.last_name|title }}
    {% else %}
      {{ consultation.doctor.username }}
    {% endif %}
    </strong>
    </p>

    <h2>Medicinas</h2>

  </article>

  {% if medicines_per_consultation %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Código</th>        
          <th>Nombre</th>        
          <th>Cantidad Suministrada</th> 
          <th>Detalle</th> 
        </tr>
      </thead>
      <tbody>
        {% for medicine_per_consultation in medicines_per_consultation %}
          <tr>
            <td>{{ medicine_per_consultation.medicine.code }}</td>
            <td>{{ medicine_per_consultation.medicine.name|title }}</td>
            <td>{{ medicine_per_consultation.amount }}</td>
            <td><a href="{% url 'medicine_app:medicines-detail' medicine_per_consultation.medicine.code %}" target="_blank"><i class="fa fa-eye"></i></a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <article class="panel-body">
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        El paciente no necesitó ser medicado!
      </div>
    </article>
  {% endif %}


  <article class="panel-body">
    <p>
      <a href="{% url 'consultation_app:medical-history' consultation.patient.dni %}" class="btn btn-success btn-block"> Volver al Historial </a>
    </p>
    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista de Pacientes </a>
    </p>
  </article>

</div>

{% endblock content %}

hospital/templates/consultation/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not consultations %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    El paciente no tiene historia clínica!
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Historial Médico</h1>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Doctor a Cargo</th>        
        <th>Diagnóstico</th>        
        <th>¿Estuvo Internado?</th>      
        <th>Fecha</th>      
        <th>Detalle</th>      
      </tr>
    </thead>
    <tbody>
      {% for consultation in consultations %}
        <tr>
          {% if consultation.doctor.first_name %}
            <td>{{ consultation.doctor.first_name|title }} {{ consultation.doctor.last_name|title }}</td>
          {% else %}
            <td>{{ consultation.doctor|title }}</td>
          {% endif %}
          <td>{{ consultation.diagnosis }}</td>
          <td>
            {% if consultation.is_inpatient %}
              <span class="glyphicon glyphicon-ok"></span>
            {% else %}
              <span class="glyphicon glyphicon-remove"></span>
            {% endif %}
          </td>
          <td>{{ consultation.date_performed|date }}</td>
          <td><a href="{% url 'consultation_app:detailed-consultation' consultation.id %}"><i class="fa fa-eye"></i></a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <article class="panel-body">
    <p>
      <a href="{% url 'consultation_app:medical-consultation' patient_dni %}" class="btn btn-success btn-block"> Realizar Consulta Médica </a>
    </p>
    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
  </article>

</div>

{% endblock content %}