hospital/expose_the_user/urls.py
from django.conf.urls import patterns, url
from .views import user_list_view, UserDetailView, UserDeleteView
from .views import user_create_view, user_update_view


urlpatterns = patterns(
    '',
    url(r'^$', user_list_view, name='users-list'),
    url(
        r'^create/$',
        user_create_view,
        name='users-create',
    ),
    url(
        r'^delete/(?P<pk>[\w]+)/$',
        UserDeleteView.as_view(),
        name='users-delete',
    ),
    url(
        r'^update/(?P<pk>[\w]+)/$',
        user_update_view,
        name='users-update',
    ),
    url(
        r'^(?P<pk>[\w]+)/$',
        UserDetailView.as_view(),
        name='users-detail',
    ),
)

hospital/home/urls.py
from django.conf.urls import patterns, url
from .views import login, logout


urlpatterns = patterns(
    '',
    url(r'^$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
)

hospital/hospital/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from rest_framework import routers
from patient.views import PatientViewSet
from expose_the_user.views import UserViewSet
from medicine.views import MedicineViewSet, MedicinePerConsultationViewSet
from consultation.views import MedicalConsultationViewSet


router = routers.DefaultRouter()
router.register(r'patients', PatientViewSet)
router.register(r'users', UserViewSet)
router.register(r'medicines', MedicineViewSet)
router.register(r'medicines-per-consultation', MedicinePerConsultationViewSet)
router.register(r'consultations', MedicalConsultationViewSet)


urlpatterns = patterns(
    '',
    # Grappelli urls.
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Browsable API.
    url(r'^api/', include(router.urls)),
    url(
        r'^api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework'
        )
    ),
    # Home app.
    url(r'^', include('home.urls', namespace='home_app')),
    # Patient app.
    url(r'^patients/', include('patient.urls', namespace='patient_app')),
    # User app.
    url(r'^users/', include('expose_the_user.urls', namespace='user_app')),
    # Medicine app.
    url(r'^medicines/', include('medicine.urls', namespace='medicine_app')),
    # Medicine app.
    url(
        r'^consultation/',
        include('consultation.urls', namespace='consultation_app')
    ),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        url(r'^rosetta/', include('rosetta.urls')),
    )

hospital/expose_the_user/models.py
from django.db import models

# Create your models here.

hospital/expose_the_user/views.py
from django.shortcuts import render_to_response
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from rest_framework import viewsets
from rest_framework import permissions
from hospital.permissions import IsSuperuserOrReadOnly
from hospital.mixins import LoginRequiredMixin
from .serializers import UserSerializer
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _


class UserViewSet(viewsets.ModelViewSet):

    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer
    permission_classes = (
        permissions.IsAuthenticatedOrReadOnly,
        IsSuperuserOrReadOnly,
    )
    filter_fields = (
        'username',
        'first_name',
        'last_name',
        'email',
        'is_superuser',
    )

    def pre_save(self, obj):
        obj.set_password(obj.password)
        super(UserViewSet, self).pre_save(obj)


def user_list_view(request):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    my_users = None
    search = request.GET.get("search", False)
    if search:
        try:
            my_users = User.objects.filter(username__icontains=search) | \
                User.objects.filter(first_name__icontains=search) | \
                User.objects.filter(last_name__icontains=search)
        except Exception, e:
            my_users = None
    else:
        my_users = User.objects.all()

    ctx = {'my_users': my_users}

    return render_to_response(
        'expose_the_user/list.html',
        ctx,
        context_instance=RequestContext(request),
    )


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'expose_the_user/detail.html'


# solo como superuser
class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = reverse_lazy('user_app:users-list')
    template_name = 'expose_the_user/delete.html'


def record_user(request):
    username = request.POST['username']
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    email = request.POST['email']
    password = request.POST['password']
    is_superuser = request.POST.get('is_superuser', False)

    user = User.objects.create(
        username=username,
        first_name=first_name,
        last_name=last_name,
        email=email,
        is_superuser=is_superuser,
    )
    user.set_password(password)
    user.save()

    return user


def user_create_view(request):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            user = record_user(request)
            if user:
                return HttpResponseRedirect(
                    reverse('user_app:users-list')
                )

        return render_to_response(
            'expose_the_user/create.html',
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])


def update_user(request, pk):
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    email = request.POST['email']
    is_superuser = request.POST.get('is_superuser', False)

    user = get_object_or_404(User, pk=pk)
    user.first_name = first_name
    user.last_name = last_name
    user.email = email
    user.is_superuser = is_superuser
    user.save()

    return user


def user_update_view(request, pk):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            user = update_user(request, pk)
            if user:
                return HttpResponseRedirect(
                    reverse('user_app:users-list')
                )

        user = get_object_or_404(User, pk=pk)

        ctx = {'my_user': user}

        return render_to_response(
            'expose_the_user/update.html',
            ctx,
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])

hospital/templates/expose_the_user/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Crear Usuario</h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}
      <div class="form-group">
        <label for="username">Usuario</label>
        <input name="username" id="username" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="first_name">Nombres</label>
        <input name="first_name" id="first_name" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="last_name">Apellidos</label>
        <input name="last_name" id="last_name" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input name="email" id="email" type="email" class="form-control">
      </div>

      <div class="form-group">
        <label for="password">Contraseña</label>
        <input name="password" id="password" type="password" class="form-control">
      </div>

      <div class="checkbox">
        <label>
          <input name="is_superuser" type="checkbox"> ¿Es superusuario?
        </label>
      </div>
      
      <p>
        <button type="submit" class="btn btn-success btn-block"/>Crear</button>
      </p>
    </form>

    <p>
      <a href="{% url 'user_app:users-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
  </article>
  
</div>

{% endblock content %}

hospital/templates/expose_the_user/delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-danger">

  <div class="panel-heading">
    <h1 class="panel-title">
      Eliminación del
      {% if object.is_superuser %}
        Superusuario <strong>{{ object.username }}</strong> <i class="fa fa-user"></i>
      {% else %}
        Médico <strong>{{ object.username }}</strong> <i class="fa fa-stethoscope"></i>
      {% endif %}
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}
      <h2>¿Está seguro que desea eliminar a <strong>{{ object }}</strong>?</h2>
      <p>
        <button type="submit" class="btn btn-danger btn-block"/>Confirmar</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'user_app:users-list' %}" class="btn btn-success btn-block"> Volver a la Lista </a>
      </p>
      <p>
        <a href="{% url 'user_app:users-update' object.pk %}" class="btn btn-primary btn-block"> Modificar Usuario </a>
      </p>
    </section>
  </article>

</div>

{% endblock content %}

hospital/templates/expose_the_user/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Detalle del
      {% if object.is_superuser %}
        Superusuario <strong>{{ object.username }}</strong> <i class="fa fa-user"></i>
      {% else %}
        Médico <strong>{{ object.username }}</strong> <i class="fa fa-stethoscope"></i>
      {% endif %}
    </h1>
  </div>

  <article class="panel-body">
    {% if object.id %}
      <p>ID: <strong>{{ object.id }}</strong></p> 
    {% endif %}
    
    {% if object.first_name %}
      <p>Nombres: <strong>{{ object.first_name|title }}</strong></p> 
    {% endif %}
    
    {% if object.last_name %}
      <p>Apellidos: <strong>{{ object.last_name|title }}</strong></p> 
    {% endif %}
    
    {% if object.email %}
      <p>Email: <strong>{{ object.email }}</strong></p> 
    {% endif %}
    
    {% if object.last_login %}
      <p>Última vez que ingreso: <strong>{{ object.last_login|date }}</strong></p> 
    {% endif %}
    
    {% if object.date_joined %}
      <p>Fecha de Creación: <strong>{{ object.date_joined|date }}</strong></p> 
    {% endif %}

    <p>
      <a href="{% url 'user_app:users-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
    <p>
      <a href="{% url 'user_app:users-update' object.id %}" class="btn btn-primary btn-block"> Modificar Usuario </a>
    </p>
    <p>
      <a href="{% url 'user_app:users-delete' object.id %}" class="btn btn-primary btn-block"> Eliminar Usuario </a>
    </p>
  </article>

</div>

{% endblock content %}

hospital/templates/expose_the_user/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not my_users %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    No hay usuarios! 
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Lista de Usuarios</h1>
  </div>
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Usuario</th>        
        <th>Nombres</th>        
        <th>Apellidos</th>        
        <th>¿Es médico?</th>        
        <th>Fecha de Creación</th>        
      </tr>
    </thead>
    <tbody>
    {% for my_user in my_users %}
      <tr>
      <td><a href="{% url 'user_app:users-detail' my_user.id %}">{{ my_user.username }}</a></td>
      <td>{{ my_user.first_name }}</td>
      <td>{{ my_user.last_name }}</td>
      <td>
        {% if my_user.is_superuser %}
          <span class="glyphicon glyphicon-remove"></span>
        {% else %}
          <span class="glyphicon glyphicon-ok"></span>
        {% endif %}
      </td>
      <td>{{ my_user.date_joined|date }}</td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

  <article class="panel-body">
    <p>
      <a href="{% url 'user_app:users-create' %}" class="btn btn-success btn-block"> Crear Usuario </a>
    </p>
  </article>

</div>

{% endblock content %}

hospital/templates/expose_the_user/update.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Modificar Usuario</h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}

      <div class="form-group">
        <label for="username">Usuario</label>
        <input name="username" id="username" type="text" class="form-control" value="{{ my_user.username }}" readonly>
      </div>

      <div class="form-group">
        <label for="first_name">Nombres</label>
        <input name="first_name" id="first_name" type="text" class="form-control" value="{{ my_user.first_name }}">
      </div>

      <div class="form-group">
        <label for="last_name">Apellidos</label>
        <input name="last_name" id="last_name" type="text" class="form-control" value="{{ my_user.last_name }}">
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input name="email" id="email" type="email" class="form-control" value="{{ my_user.email }}">
      </div>

      <div class="checkbox">
        <label>
          <input name="is_superuser" type="checkbox" value="{{ my_user.is_superuser }}" {% if my_user.is_superuser %} checked {% endif %}> ¿Es superusuario?
        </label>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/>Modificar</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'user_app:users-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
      </p>
      <p>
        <a href="{% url 'user_app:users-delete' my_user.pk %}" class="btn btn-primary btn-block"> Eliminar Usuario </a>
      </p>
    </section>
  </article>

</div>

{% endblock content %}