hospital/consultation/urls.py
from django.conf.urls import patterns, url
from .views import medical_consultation, medical_history
from .views import detailed_consultation


urlpatterns = patterns(
    '',
    url(
        r'^(?P<dni>[\w]+)/$',
        medical_consultation,
        name='medical-consultation',
    ),
    url(
        r'^history/(?P<dni>[\w]+)/$',
        medical_history,
        name='medical-history',
    ),
    url(
        r'^detail/(?P<pk>[\w]+)/$',
        detailed_consultation,
        name='detailed-consultation',
    ),
)

hospital/home/urls.py
from django.conf.urls import patterns, url
from .views import login, logout


urlpatterns = patterns(
    '',
    url(r'^$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
)

hospital/hospital/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

from rest_framework import routers
from patient.views import PatientViewSet
from expose_the_user.views import UserViewSet
from medicine.views import MedicineViewSet, MedicinePerConsultationViewSet
from consultation.views import MedicalConsultationViewSet


router = routers.DefaultRouter()
router.register(r'patients', PatientViewSet)
router.register(r'users', UserViewSet)
router.register(r'medicines', MedicineViewSet)
router.register(r'medicines-per-consultation', MedicinePerConsultationViewSet)
router.register(r'consultations', MedicalConsultationViewSet)


urlpatterns = patterns(
    '',
    # Grappelli urls.
    (r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # Browsable API.
    url(r'^api/', include(router.urls)),
    url(
        r'^api-auth/',
        include(
            'rest_framework.urls',
            namespace='rest_framework'
        )
    ),
    # Home app.
    url(r'^', include('home.urls', namespace='home_app')),
    # Patient app.
    url(r'^patients/', include('patient.urls', namespace='patient_app')),
    # User app.
    url(r'^users/', include('expose_the_user.urls', namespace='user_app')),
    # Medicine app.
    url(r'^medicines/', include('medicine.urls', namespace='medicine_app')),
    # Medicine app.
    url(
        r'^consultation/',
        include('consultation.urls', namespace='consultation_app')
    ),
)


if settings.DEBUG:
    urlpatterns += patterns(
        '',
        (
            r'^media/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        )
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns(
        '',
        url(r'^rosetta/', include('rosetta.urls')),
    )

hospital/patient/urls.py
from django.conf.urls import patterns, url
from .views import patient_list_view, PatientDetailView, PatientDeleteView
from .views import patient_create_view, patient_update_view


urlpatterns = patterns(
    '',
    url(r'^$', patient_list_view, name='patients-list'),
    url(
        r'^create/$',
        patient_create_view,
        name='patients-create',
    ),
    url(
        r'^delete/(?P<pk>[\w]+)/$',
        PatientDeleteView.as_view(),
        name='patients-delete',
    ),
    url(
        r'^update/(?P<dni>[\w]+)/$',
        patient_update_view,
        name='patients-update',
    ),
    url(
        r'^(?P<pk>[\w]+)/$',
        PatientDetailView.as_view(),
        name='patients-detail',
    ),
)

hospital/patient/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, RegexValidator
from django.utils.translation import ugettext_lazy as _


class Patient(models.Model):
    dni = models.CharField(
        max_length=8,
        primary_key=True,
        validators=[
            RegexValidator(
                r'^\d{8}',
                _('only valid DNIs are allowed'),
                _('invalid DNI'),
            ),
        ],
    )
    superuser = models.ForeignKey(
        User,
        verbose_name=_('superuser'),
    )
    first_name = models.CharField(
        max_length=100,
        verbose_name=_('first name'),
    )
    last_name = models.CharField(
        max_length=100,
        verbose_name=_('last name'),
    )
    age = models.PositiveIntegerField(
        validators=[
            MaxValueValidator(150),
        ],
        verbose_name=_('age'),
    )

    MALE = 'M'
    FEMALE = 'F'
    OTHER = 'O'
    SEX = (
        (MALE, _('male')),
        (FEMALE, _('female')),
        (OTHER, _('other')),
    )
    sex = models.CharField(
        max_length=1,
        choices=SEX,
        default=MALE,
        verbose_name=_('sex'),
    )
    address = models.CharField(
        max_length=200,
        blank=True,
        verbose_name=_('address'),
    )
    email = models.EmailField(
        max_length=150,
        blank=True,
        verbose_name=_('email'),
    )
    telephone = models.CharField(
        max_length=15,
        blank=True,
        verbose_name=_('telephone'),
    )
    cellphone = models.CharField(
        max_length=15,
        blank=True,
        verbose_name=_('cellphone'),
    )
    is_inpatient = models.BooleanField(
        default=False,
        verbose_name=_('is inpatient'),
    )
    date_joined = models.DateTimeField(
        default=timezone.now,
        verbose_name=_('date joined'),
    )

    def __unicode__(self):
        return unicode(self.dni)

    class Meta:
        db_table = 'patient'
        verbose_name = _('patient')

hospital/patient/views.py
from django.shortcuts import render_to_response
from rest_framework import viewsets
from rest_framework import permissions
from hospital.permissions import IsSuperuserOrReadOnly
from hospital.mixins import LoginRequiredMixin
from .serializers import PatientSerializer
from .models import Patient
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import DeleteView
from django.template import RequestContext
from django.core.urlresolvers import reverse, reverse_lazy
from django.http import HttpResponseRedirect, HttpResponseNotAllowed
from django.shortcuts import get_object_or_404
from django.utils.translation import ugettext_lazy as _


class PatientViewSet(viewsets.ModelViewSet):

    queryset = Patient.objects.all()
    serializer_class = PatientSerializer
    permission_classes = (
        permissions.IsAuthenticatedOrReadOnly,
        IsSuperuserOrReadOnly,
    )
    filter_fields = (
        'superuser',
        'first_name',
        'last_name',
        'sex',
        'email',
        'telephone',
        'cellphone',
        'is_inpatient',
    )

    def pre_save(self, obj):
        user = self.request.user
        obj.superuser = user
        super(PatientViewSet, self).pre_save(obj)


def patient_list_view(request):
    if not request.user.is_authenticated():
        return HttpResponseNotAllowed(['GET'])

    patients = None
    search = request.GET.get("search", False)
    if search:
        try:
            patients = Patient.objects.filter(dni__icontains=search) | \
                Patient.objects.filter(first_name__icontains=search) | \
                Patient.objects.filter(last_name__icontains=search)
        except Exception, e:
            patients = None
    else:
        patients = Patient.objects.all()

    ctx = {'patients': patients}

    return render_to_response(
        'patient/list.html',
        ctx,
        context_instance=RequestContext(request),
    )


class PatientDetailView(LoginRequiredMixin, DetailView):
    model = Patient
    template_name = 'patient/detail.html'


# solo como superuser
class PatientDeleteView(LoginRequiredMixin, DeleteView):
    model = Patient
    success_url = reverse_lazy('patient_app:patients-list')
    template_name = 'patient/delete.html'


def record_patient(request):
    dni = request.POST['dni']
    superuser = request.user
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    age = request.POST['age']
    sex = request.POST['sex']
    address = request.POST['address']
    email = request.POST['email']
    telephone = request.POST['telephone']
    cellphone = request.POST['cellphone']
    is_inpatient = request.POST.get('is_inpatient', False)

    patient = Patient.objects.create(
        dni=dni,
        superuser=superuser,
        first_name=first_name,
        last_name=last_name,
        age=age,
        sex=sex,
        address=address,
        email=email,
        telephone=telephone,
        cellphone=cellphone,
        is_inpatient=is_inpatient,
    )

    return patient


def patient_create_view(request):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            patient = record_patient(request)
            if patient:
                return HttpResponseRedirect(
                    reverse('patient_app:patients-list')
                )

        return render_to_response(
            'patient/create.html',
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])


def update_patient(request, dni):
    first_name = request.POST['first_name']
    last_name = request.POST['last_name']
    age = request.POST['age']
    sex = request.POST['sex']
    address = request.POST['address']
    email = request.POST['email']
    telephone = request.POST['telephone']
    cellphone = request.POST['cellphone']
    is_inpatient = request.POST.get('is_inpatient', False)

    patient = get_object_or_404(Patient, pk=dni)
    patient.first_name = first_name
    patient.last_name = last_name
    patient.age = age
    patient.sex = sex
    patient.address = address
    patient.email = email
    patient.telephone = telephone
    patient.cellphone = cellphone
    patient.is_inpatient = is_inpatient
    patient.save()

    return patient


def patient_update_view(request, dni):
    if request.user.is_authenticated() and request.user.is_superuser:
        if request.method == "POST":
            patient = update_patient(request, dni)
            if patient:
                return HttpResponseRedirect(
                    reverse('patient_app:patients-list')
                )

        patient = get_object_or_404(Patient, pk=dni)

        ctx = {'patient': patient}

        return render_to_response(
            'patient/update.html',
            ctx,
            context_instance=RequestContext(request),
        )

    return HttpResponseNotAllowed(['GET'])

hospital/templates/patient/create.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Crear Paciente</h1>
  </div>

  <article class="panel-body">
    <form action="" method="post" role="form">
      {% csrf_token %}
      <div class="form-group">
        <label for="dni">DNI</label>
        <input name="dni" id="dni" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="first_name">Nombres</label>
        <input name="first_name" id="first_name" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="last_name">Apellido</label>
        <input name="last_name" id="last_name" type="text" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="age">Edad</label>
        <input name="age" id="age" type="number" class="form-control" required>
      </div>

      <div class="form-group">
        <label for="sex">Sexo</label>
        <select name="sex" id="sex" class="form-control" required>
          <option value="M">Masculino</option>
          <option value="F">Femenino</option>
        </select>
      </div>

      <div class="form-group">
        <label for="address">Dirección</label>
        <input name="address" id="address" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="email">Email</label>
        <input name="email" id="email" type="email" class="form-control">
      </div>

      <div class="form-group">
        <label for="telephone">Teléfono</label>
        <input name="telephone" id="telephone" type="text" class="form-control">
      </div>

      <div class="form-group">
        <label for="cellphone">Celular</label>
        <input name="cellphone" id="cellphone" type="text" class="form-control">
      </div>

      <div class="checkbox">
        <label>
          <input name="is_inpatient" type="checkbox"> ¿Está Internado?
        </label>
      </div>

      <p>
        <button type="submit" class="btn btn-success btn-block"/> Crear</button>
      </p>
    </form>

    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
  </article>

{% endblock content %}

hospital/templates/patient/delete.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-danger">

  <div class="panel-heading">
    <h1 class="panel-title">
      Eliminación del Paciente <strong>{{ object.first_name|title }} {{ object.last_name|title }}</strong> <i class="fa fa-trash"></i>
    </h1>
  </div>

  <article class="panel-body">
    <form action="" method="post">
      {% csrf_token %}
      <h2>¿Está seguro que desea eliminar a <strong>{{ object.first_name|title }} {{ object.last_name|title }}</strong> identificado con DNI: <strong>{{ object }}</strong>?</h2>
      <p>
        <button type="submit" class="btn btn-danger btn-block"/>Confirmar</button>
      </p>
    </form>

    <section>
      <p>
        <a href="{% url 'patient_app:patients-list' %}" class="btn btn-success btn-block"> Volver a la Lista </a>
      </p>
      <p>
        <a href="{% url 'patient_app:patients-update' object.dni %}" class="btn btn-primary btn-block"> Modificar Paciente </a>
      </p>
    </section>

  </article>

</div>

{% endblock content %}

hospital/templates/patient/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">
      Detalle del Paciente <strong>{{ object.first_name|title }} {{ object.last_name|title }}</strong> <i class="fa fa-wheelchair"></i>
    </h1>
  </div>

  <article class="panel-body">
    {% if object.is_inpatient %}
      <div class="alert alert-warning" role="alert">El paciente <strong>se encuentra internado!</strong></div>
    {% else %}
      <div class="alert alert-success" role="alert">El paciente <strong>NO se encuentra internado...</strong></div>
    {% endif %}

    {% if object.dni %}
      <p>DNI: <strong>{{ object.dni }}</strong></p>
    {% endif %}
    
    {% if object.superuser %}
      <p>Creador: <strong>{{ object.superuser.username }}</strong></p>
    {% endif %}
    
    {% if object.first_name %}
      <p>Nombres: <strong>{{ object.first_name|title }}</strong></p>
    {% endif %}
    
    {% if object.last_name %}
      <p>Apellidos: <strong>{{ object.last_name|title }}</strong></p>
    {% endif %}
    
    {% if object.age %}
      <p>Edad: <strong>{{ object.age }}</strong></p>
    {% endif %}
    
    {% if object.sex %}
      <p>Sexo: <strong>{{ object.sex }}</strong></p>
    {% endif %}
    
    {% if object.address %}
      <p>Dirección: <strong>{{ object.address }}</strong></p>
    {% endif %}
    
    {% if object.email %}
      <p>Email: <strong>{{ object.email }}</strong></p>
    {% endif %}
    
    {% if object.telephone %}
      <p>Teléfono: <strong>{{ object.telephone }}</strong></p>
    {% endif %}
    
    {% if object.telephone %}
      <p>Celular: <strong>{{ object.cellphone }}</strong></p>
    {% endif %}
    
    {% if object.date_joined %}
      <p>Fecha de Creación: <strong>{{ object.date_joined|date }}</strong></p>
    {% endif %}

    <p>
      <a href="{% url 'patient_app:patients-list' %}" class="btn btn-primary btn-block"> Volver a la Lista </a>
    </p>
    <p>
      <a href="{% url 'patient_app:patients-update' object.dni %}" class="btn btn-primary btn-block"> Modificar Paciente </a>
    </p>
    <p>
      <a href="{% url 'patient_app:patients-delete' object.dni %}" class="btn btn-primary btn-block"> Eliminar Paciente </a>
    </p>
  </article>

</div>

{% endblock content %}

hospital/templates/patient/list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}

{% if not patients %}
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    Aún no hay pacientes! 
    {% if user.is_superuser %}
      <a href="{% url 'patient_app:patients-create' %}">
        Por favor ingrese uno</a>.
    {% endif %}
  </div>
{% endif %}

<div class="panel panel-primary">

  <div class="panel-heading">
    <h1 class="panel-title">Lista de Pacientes</h1>
  </div>


  <table class="table table-striped">
    <thead>
      <tr>
        <th>DNI</th>        
        <th>Nombres</th>        
        <th>Apellidos</th>        
        <th>Edad</th>        
        <th>Sexo</th>        
        <th>Email</th>        
        <th>¿Está Internado?</th>        
        <th>Reclutador</th>        
        <th>Fecha de Creación</th>        
        <th>Historial</th>        
        <th>Consulta</th>        
      </tr>
    </thead>
    <tbody>
      {% for patient in patients %}
        <tr>
          <td><a href="{% url 'patient_app:patients-detail' patient.dni %}">{{ patient.dni }}</a></td>
          <td>{{ patient.first_name }}</td>
          <td>{{ patient.last_name }}</td>
          <td>{{ patient.age }}</td>
          <td>
            {% if patient.sex == 'M' %}
              <i class="fa fa-male"></i> M
            {% else %}
              <i class="fa fa-female"></i> F
            {% endif %}
          </td>
          <td>{{ patient.email }}</td>
          <td>
            {% if patient.is_inpatient %}
              <span class="glyphicon glyphicon-ok"></span>
            {% else %}
              <span class="glyphicon glyphicon-remove"></span>
            {% endif %}
          </td>
          <td>{{ patient.superuser.username }}</td>
          <td>{{ patient.date_joined|date }}</td>
          <td>
            <a href="{% url 'consultation_app:medical-history' patient.dni %}"><i class="fa fa-file-text"></i></a>
          </td>
          <td>
            <a href="{% url 'consultation_app:medical-consultation' patient.dni %}"><i class="fa fa-stethoscope"></i></a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% if user.is_superuser %}
    <article class="panel-body">
      <p>
        <a href="{% url 'patient_app:patients-create' %}" class="btn btn-success btn-block"> Crear Paciente </a>
      </p>
    </article>
  {% endif %}

</div>

{% endblock content %}